services:
  memo-ghost-server:
    image: ghost:6.10.3
    container_name: memo-ghost-server
    restart: unless-stopped
    env_file: .env
    environment:
      url: ${SITE_URL}
      database__client: mysql
      database__connection__host: memo-ghost-db
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}
    ports:
      - "2368:2368"
    volumes:
      - ghost_content:/var/lib/ghost/content
    depends_on:
      - memo-ghost-db

  memo-ghost-db:
    image: mariadb:10.6
    container_name: memo-ghost-db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  ghost_content:
  db_data:
