services:
  memo-wordpress-server:
    image: wordpress:latest
    container_name: memo-wordpress-server
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: memo-wp-db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "2368:80"
    volumes:
      - memo_wp_server_data:/var/www/html
    depends_on:
      - memo-wp-db

  memo-wp-db:
    image: mariadb:10.6
    container_name: memo-wp-db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - memo_wp_db_data:/var/lib/mysql

volumes:
  memo_wp_server_data:
  memo_wp_db_data:
